services:
  medassist:
    container_name: medassisttest
    image: ghcr.io/Wolbaz/medassist:beta
    restart: always
    environment:
      - TZ=Etc/UTC
    ports:
      - 3112:3111
    volumes:
      - /mnt/user/appdata/medassisttest/database:/app/database