services:
  medassist:
    container_name: medassist
    image: ghcr.io/njic/medassist:latest
    environment:
      - TZ=Etc/UTC
    ports:
      - 3111:3111
    volumes:
      - /path/to/database/directory:/app/medassist